package cs3240project;

/**
 * Tokens generated by spec scanner for the spec parser
 */

public class SpecToken extends Token {

    /**
     * Create a new spec token
     * @param type class of token
     * @param instance value in the source, literal instance
     */

    public SpecToken(String type, String instance) {
        super(type, instance);
    }
}
